- name: Use own sources.list
  become: true
  ansible.builtin.template:
    src: templates/sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Update packages
  become: true
  package:
    update_cache: yes

- name: Upgrade packages
  become: true
  package:
    upgrade: yes
  when: upgrade is not defined or upgrade

- name: Install packages
  become: true
  block:
    - name: Install from stable
      package:
        name: "{{ packages }}"
        state: latest
      when: packages is defined
    - name: Install from backports
      package:
        name: "{{ backports.packages }}"
        state: latest
        default_release: "{{ backports.distribution }}"
      when: backports is defined

- name: Create symlinks
  become: false
  block:
    - name: Create ~/.local/bin dir
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory
    - name: Create symlink to Python3
      ansible.builtin.file:
        src: /usr/bin/ipython3
        dest: ~/.local/bin/ipython
        state: link
