- hosts: localhost
  roles:
    # - apt
    - librewolf
    # - flatpak
    # - gnome-extensions
    # - gnome-configs
    # - zsh
    # - neovim
    # - miniforge
    # - dotfiles
    # - grub
    # - bluetooth
