- hosts: localhost
  roles:
    - apt
    - librewolf
    - syncthing
    - flatpak
    - gnome-configs
    - gnome-extensions
    - zsh
    # - neovim
    - helix
    - miniforge
    - dotfiles
    - grub
    - bluetooth
