- name: Configure GNOME's feel and look
  when: config_look_and_feel
  block:
  - name: Install icon packages
    become: true
    package:
      name: papirus-icon-theme
      state: latest
  - name: Set Papirus icons
    dconf:
      key: "/org/gnome/desktop/interface/icon-theme"
      value: "'Papirus-Dark'"
  - name: Configure dark color scheme
    dconf:
      key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"
  - name: Configure GNOME theme
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
  - name: Show battery percentage in topbar
    dconf:
      key: "/org/gnome/desktop/interface/show-battery-percentage"
      value: "true"
  - name: Disable dynamic workspaces
    dconf:
      key: "/org/gnome/mutter/dynamic-workspaces"
      value: "false"
  - name: Set number of workspaces
    dconf:
      key: "/org/gnome/desktop/wm/preferences/num-workspaces"
      value: "false"
  - name: Configure touchpad (touch area)
    dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/click-method"
      value: "'areas'"
  - name: Configure touchpad (scroll)
    dconf:
      key: "/org/gnome/desktop/peripherals/touchpad/natural-scroll"
      value: "false"
  - name: Configure Caps Lock as extra escape
    dconf:
      key: "/org/gnome/desktop/input-sources/xkb-options"
      value: ['caps:escape']
  - name: Disable event sounds
    dconf:
      key: "/org/gnome/desktop/sound/event-sounds"
      value: "false"
  - name: Enable minimize and maximize buttons in windows
    dconf:
      key: "/org/gnome/desktop/wm/preferences/button-layout"
      value: "'appmenu:minimize,maximize,close'"
  - name: Workspaces in all displays
    dconf:
      key: "/org/gnome/mutter/workspaces-only-on-primary"
      value: "false"

- name: Configure nautilus and file chooser
  block:
    - name: Set list view as the default
      dconf:
        key: "/org/gnome/nautilus/preferences/default-folder-viewer"
        value: "'list-view'"
    - name: Sort directories first (gtk4)
      dconf:
        key: "/org/gtk/gtk4/settings/file-chooser/sort-directories-first"
        value: "true"
    - name: Sort directories first (gtk)
      dconf:
        key: "/org/gtk/settings/file-chooser/sort-directories-first"
        value: "true"
    - name: Default columns in list view
      dconf:
        key: "/org/gnome/nautilus/list-view/default-visible-columns"
        value: ['name', 'type', 'size', 'date_modified']

- name: Setup environmental variables
  become: true
  ansible.builtin.template:
    src: templates/99-env-vars.conf
    dest: /etc/environment.d/99-env-vars.conf
    owner: root
    group: root
    mode: '0644'
    backup: true

- name: Keyboard Shortcuts
  when: config_keyboard_shortcuts
  block:
    - name: Remove shortcuts to favourite applications
      dconf:
        key: "/org/gnome/shell/keybindings/switch-to-application-{{ item }}"
        value: ['']
      loop: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    - name: Shortcuts to switch workspaces
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-{{ item }}"
        value: ['<Super>{{ item }}']
      loop: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    - name: Shortcuts to move windows to workspaces
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-{{ item }}"
        value: ['<Super><Shift>{{ item }}']
      loop: [1, 2, 3, 4, 5, 6, 7, 8, 9]
    - name: Shortcuts to move windows to monitor up
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-up"
        value: ['<Super><Shift>Up','<Super><Control>k']
    - name: Shortcuts to move windows to monitor down
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-down"
        value: ['<Super><Shift>Down','<Super><Control>j']
    - name: Shortcuts to move windows to monitor left
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-left"
        value: ['<Super><Shift>Left','<Super><Control>h']
    - name: Shortcuts to move windows to monitor right
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-right"
        value: ['<Super><Shift>Right','<Super><Control>l']
    - name: Close windows
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/close"
        value: ['<Super>q']
    - name: Full screen
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/toggle-fullscreen"
        value: ['<Super>f']
    - name: Hide application
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/minimize"
        value: ['<Super>m']
    - name: Lockscreen (override to not use Super+l)
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
        value: ['<Super>Escape']
    - name: Tiling right
      dconf:
        key: "/org/gnome/mutter/keybindings/toggle-tiled-right"
        value: ['<Super>Right', '<Super><Shift>l']
    - name: Tiling left
      dconf:
        key: "/org/gnome/mutter/keybindings/toggle-tiled-left"
        value: ['<Super>Left','<Super><Shift>h']
    - name: Maximize
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/toggle-maximized"
        value: ['<Alt>F10','<Super>i']
    - name: Use Super+d and Super+s for launching overview
      dconf:
        key: "/org/gnome/shell/keybindings/toggle-overview"
        value: ['<Super>s', '<Super>d']
    - name: Make sure to use super key for overview
      dconf:
        key: "/org/gnome/mutter/overlay-key"
        value: "'Super_L'"
    - name: Switch to workspace left
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left"
        value: ['<Super>Page_Up', '<Super><Alt>Left', '<Control><Alt>Left', '<Super>bracketleft']
    - name: Switch to workspace right
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right"
        value: ['<Super>Page_Down', '<Super><Alt>Right', '<Control><Alt>Right', '<Super>bracketright']
    - name: Move window to workspace left
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
        value: ['<Super><Shift>Page_Up', '<Super><Shift><Alt>Left', '<Control><Shift><Alt>Left', '<Super><Shift>bracketleft']
    - name: Move window to workspace right
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
        value: ['<Super><Shift>Page_Down', '<Super><Shift><Alt>Right', '<Control><Shift><Alt>Right', '<Super><Shift>bracketright']
