# --------------------------------------
# Install and configure GNOME Extensions
# --------------------------------------
- name: Install GNOME extensions
  become: true
  package:
    name:
      - "{{ item }}"
  with_items: "{{ extensions }}"
